### ISSUE TITLE
WSL 2 support?

### ISSUE THREAD

**Issue by RafOXxxx** [ChristianKohler/PathIntellisense#190] opened 2021-10-15 20:14 UTC
Does this extension support working with WSL 2 or remote servers respectively?
After installation I get the message _"This extension is enabled in the Remote Extension Host because it prefers to run there."_, unfortunately it does not give me any path suggestions.

**Comment by ChristianKohler** [comment] 2021-11-01 10:45
@RafOXxxx Could you tell me more about your project setup? If it is open source, could you give me the repo and a step by step description how I can reproduce it?

**Comment by RafOXxxx** [comment] 2021-11-02 11:24
@ChristianKohler

OS: 	Windows 11
WSL: 	Ubuntu 20.04 LTS
VSCode: 1.61.2


I have created an Angular application by using Angular-CLI and added some components and services.
The file structure looks like this.

```
├── node_modules
...
├── package.json
├── functions
│   ├── lib
│   ├── node_modules
│   └── src
├── public
└── src
    ├── app
    │   ├── components
    │   │   ├── dashboard
    │   │   ├── login
    │   │   ├── logout
    │   │   ├── navigation
    │   │   ├── sign-up
    │   │   └── user
    │   └── services
    ├── assets
    └── environments
...
├── tsconfig.json
...
```



This is my `package.json`

```
{
  "name": "order-this",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "tsc --noEmit && eslint . --ext js,ts,json --quiet --fix",
    "rename": "echo \"Error: no test specified\" && exit 1"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/cdk": "^12.2.8",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/fire": "^7.0.4",
    "@angular/forms": "~12.2.0",
    "@angular/material": "^12.2.8",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "firebase": "^9.1.1",
    "firebase-admin": "^9.12.0",
    "firebase-functions": "^3.15.7",
    "firebase-tools": "^9.19.0",
    "rxfire": "^6.0.2",
    "rxjs": "~6.6.0",
    "socket.io": "^3.1.2",
    "socket.io-client": "^4.2.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1200.0",
    "@angular-devkit/build-angular": "~12.2.2",
    "@angular/cli": "~12.2.2",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^4.31.2",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-angular": "^4.1.0",
    "eslint-plugin-prettier": "^4.0.0",
    "firebase-tools": "^9.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.8.0",
    "jsonc-parser": "^3.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "open": "^7.0.3",
    "prettier": "^2.4.1",
    "prettier-eslint": "^13.0.0",
    "typescript": "~4.3.5"
  }
}
```

and this is my `tsconfig.json`

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./src/",
        "paths": {
            "@components/*": ["app/components/*"],
            "@services/*": ["app/services/*"],
            "@envs/*": ["environments/*"]
        },
        "outDir": "./dist/out-tsc",
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "es2017",
        "module": "es2020",
        "lib": ["es2018", "dom"]
    },
    "angularCompilerOptions": {
        "enableI18nLegacyMessageIdFormat": false,
        "strictInjectionParameters": true,
        "strictInputAccessModifiers": true,
        "strictTemplates": true
    }
}
```

**Comment by ChristianKohler** [comment] 2021-11-04 20:48
Thank you @RafOXxxx for your help.

Should be fixed with the latest (2.4.2) release.

Could you test it locally and with wsl and confirm that it works?

**Comment by RafOXxxx** [comment] 2021-11-04 23:53
Thank you @ChristianKohler, looks like it fixed it. :thumbsup:
Unfortunately something is still off. 
I added this to my settings.js 
```
"path-intellisense.mappings": {
        "@services": "${workspaceFolder}/src/app/services/"
    }
```
When I type in `import {} from '@services/';`,
it will suggest all files inside  "${workspaceFolder}/src/app/services/",
if I only type in `import {} from '@';`,
I would expect to get "@angular" and "@services" as a suggestion , but I get neither.

**Comment by ChristianKohler** [comment] 2021-11-05 08:23
Great. Thanks for testing 🙏. Happy to hear that it works.

> if I only type in import {} from '@';,
I would expect to get "@angular" and "@services" as a suggestion , but I get neither.

The extension doesn't autocomplete mapping keys like `@services`. Haven't thought about that as often the mappings are short.

Closing this issue since the bug itself is closed.

**Closed by ChristianKohler** 2021-11-05 08:23 UTC
