### ISSUE TITLE
dont work in vscode 1.6

### ISSUE THREAD

**Issue by minjunlan** [ChristianKohler/PathIntellisense#31] opened 2016-10-13 05:00 UTC
it dont work in vscode 1.6

**Comment by kumarharsh** [comment] 2016-10-13 06:23
duplicate of https://github.com/ChristianKohler/PathIntellisense/issues/30

**Comment by ChristianKohler** [comment] 2016-10-13 08:25
@minjunlan Is it still not working after a restart?
Closed since it is a duplicate of #30

**Closed by ChristianKohler** 2016-10-13 08:25 UTC
