### ISSUE TITLE
Cannot find module 'json5' error on VSCode startup inside Dev Tools

### ISSUE THREAD

**Issue by richierich25** [ChristianKohler/PathIntellisense#164] opened 2020-06-11 17:58 UTC
Observing error from the developer tools of VSCode on start. 

**`Activating extension christian-kohler.path-intellisense' failed: Cannot find module 'json5'** 

_Error Stack:_
```error
Require stack:
- c:\Users\triph\.vscode\extensions\christian-kohler.path-intellisense-2.2.0\out\configuration\tsconfig.service.js
- c:\Users\triph\.vscode\extensions\christian-kohler.path-intellisense-2.2.0\out\configuration\configuration.service.js
- c:\Users\triph\.vscode\extensions\christian-kohler.path-intellisense-2.2.0\out\providers\javascript\javascript.provider.js
- c:\Users\triph\.vscode\extensions\christian-kohler.path-intellisense-2.2.0\out\providers\default.provider.js
- c:\Users\triph\.vscode\extensions\christian-kohler.path-intellisense-2.2.0\out\providers\index.js
- c:\Users\triph\.vscode\extensions\christian-kohler.path-intellisense-2.2.0\out\extension.js
- c:\Users\triph\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\triph\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\triph\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```

I am running VSCode `1.46` and running `Windows 10 64 bit`

**Comment by ChristianKohler** [comment] 2020-06-12 10:20
duplicate of #163

**Closed by ChristianKohler** 2020-06-12 10:20 UTC
